INSERT INTO crags (crag_name, region_name)
VALUES ('Alcatraz',                     'Miller Fork'),
       ('Camelot',                      'Miller Fork'),
       ('Chaos',                        'Miller Fork'),
       ('Cloud 9',                      'Miller Fork'),
       ('Cooper''s Cove',               'Miller Fork'),
       ('Corner Pocket',                'Miller Fork'),
       ('Deep End',                     'Miller Fork'),
       ('Fruit Wall',                   'Miller Fork'),
       ('Graveyard',                    'Miller Fork'),
       ('The Hal Garner Memorial Crag', 'Miller Fork'),
       ('Highlands',                    'Miller Fork'),
       ('The Infirmary',                'Miller Fork'),
       ('The Laboratory',               'Miller Fork'),
       ('Monastery',                    'Miller Fork'),
       ('The Morgue',                   'Miller Fork'),
       ('The Nursery',                  'Miller Fork'),
       ('The Pharmacy',                 'Miller Fork'),
       ('The Portal',                   'Miller Fork'),
       ('Rando Crag',                   'Miller Fork'),
       ('Real Deep End',                'Miller Fork'),
       ('The Record Shop',              'Miller Fork'),
       ('Sanitarium',                   'Miller Fork'),
       ('Scotch Wall',                  'Miller Fork'),
       ('Secret Garden',                'Miller Fork'),
       ('Serenity Point',               'Miller Fork'),
       ('Vine Wall',                    'Miller Fork');